In [6]:
import pandas as pd
import re

In [14]:
df = pd.read_csv('controles_surete.csv')

In [15]:
df["heure_de_debut"].max()

'2026-04-20 09:16:33'

In [16]:
df

,id,heure_de_debut,heure_de_fin,date,lieu_de_la_verification,appartenance_du_conducteur,type_de_verification,region,presence_licence_transport,numero_licence,...,is_surete,anomalie_suivi_de_tournee,agences_antennes,tournee,pda,jour,heure_arrondie,anomalie_list,anomalie_vehicule_list,anomalie_tournee_list
0,1,2026-02-10 05:12:23,2026-02-10 05:14:39,2026-02-06 00:00:00,Agence / Antenne,DSP,Avant chargement,REGION OUEST,"Oui, licence de transport intérieur",6,...,False,['Aucune anomalie'],CE16,169110,H,Mardi,05:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
1,2,2026-02-10 07:38:26,2026-02-10 07:46:36,2026-02-10 00:00:00,Agence / Antenne,DSP,Après chargement,REGION NORD,"Oui, licence de transport intérieur",3,...,False,['Aucune anomalie'],CE17,179496,A,Mardi,07:30:00,['Colis non scanné (prévu pour ce chauffeur-li...,['Aucune anomalie'],['Aucune anomalie']
2,3,2026-02-10 07:50:26,2026-02-10 07:51:44,2026-02-10 00:00:00,Agence / Antenne,DSP,Avant chargement,REGION OUEST,"Oui, licence de transport intérieur",2023/11/0002115,...,False,['Aucune anomalie'],AT7801,187889,V,Mardi,08:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
3,4,2026-02-10 07:53:16,2026-02-10 08:05:55,2026-02-10 00:00:00,Agence / Antenne,DSP,Avant chargement,REGION OUEST,"Oui, licence de transport intérieur",2025/11/0002097,...,False,['Aucune anomalie'],CE12,121451,D,Mardi,08:00:00,['Colis non scanné (prévu pour ce chauffeur-li...,['Aucune anomalie'],['Aucune anomalie']
4,5,2026-02-10 08:07:10,2026-02-10 08:08:32,2026-02-10 00:00:00,Agence / Antenne,DSP,Avant chargement,REGION OUEST,"Oui, licence de transport intérieur",2023/11/0002115,...,False,['Aucune anomalie'],AT7801,187890,A,Mardi,08:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3087,3088,2026-04-17 10:02:58,2026-04-17 10:04:34,2026-04-17 00:00:00,Agence / Antenne,DSP,Après chargement,REGION SUD EST,NaN,NaN,...,True,['Aucune anomalie'],CE28,286959 MLN TRANSPORT,C,Vendredi,10:00:00,['Colis en cabine'],['Clef laissé sur le contact'],['Aucune anomalie']
3088,3089,2026-04-17 10:04:42,2026-04-17 10:06:04,2026-04-17 00:00:00,Agence / Antenne,DSP,Après chargement,REGION SUD EST,NaN,NaN,...,True,['Aucune anomalie'],CE28,286959 MLN TRANSPORT,B,Vendredi,10:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
3089,3090,2026-04-17 10:06:06,2026-04-17 10:07:54,2026-04-17 00:00:00,Agence / Antenne,DSP,Après chargement,REGION SUD EST,NaN,NaN,...,True,['Aucune anomalie'],CE28,286961 KLF EXPRESS,D,Vendredi,10:00:00,['Colis en cabine'],['Aucune anomalie'],['Aucune anomalie']
3090,3091,2026-04-18 10:26:19,2026-04-18 10:28:31,2026-04-18 00:00:00,Agence / Antenne,DSP,Après chargement,REGION SUD EST,NaN,NaN,...,True,['Aucune anomalie'],CE08,081334,A,Samedi,10:30:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
3091,3092,2026-04-18 12:22:32,2026-04-18 12:23:31,2026-04-18 00:00:00,Agence / Antenne,DSP,Après chargement,REGION IDF,NaN,NaN,...,True,['Aucune anomalie'],NaN,187525 (BU ASMB TRANSPORT),B,Samedi,12:30:00,['Autre'],['Aucune anomalie'],['Aucune anomalie']

In [9]:
df[df["is_surete"] == True]

,id,heure_de_debut,heure_de_fin,date,lieu_de_la_verification,appartenance_du_conducteur,type_de_verification,region,presence_licence_transport,numero_licence,...,is_surete,anomalie_suivi_de_tournee,agences_antennes,tournee,pda,jour,heure_arrondie,anomalie_list,anomalie_vehicule_list,anomalie_tournee_list
1794,1795,2026-01-02 12:49:58,2026-01-02 12:53:11,2026-01-02 00:00:00,Agence / Antenne,COLIS PRIVE,Après chargement,REGION EST,NaN,NaN,...,True,['Aucune anomalie'],CE28,148269 COLIS PRIVE,O,Vendredi,13:00:00,"['Colis en cabine', 'Adhésif Colis Privé dans ...",['Aucune anomalie'],['Aucune anomalie']
1795,1796,2026-01-05 09:34:22,2026-01-05 09:35:28,2026-01-05 00:00:00,Agence / Antenne,DSP,Après chargement,REGION NORD,NaN,NaN,...,True,['Aucune anomalie'],CE15,159561,I,Lundi,09:30:00,['Colis en cabine'],['Aucune anomalie'],['Aucune anomalie']
1796,1797,2026-01-05 09:35:29,2026-01-05 09:37:59,2026-01-05 00:00:00,Agence / Antenne,DSP,Après chargement,REGION NORD,NaN,NaN,...,True,['Aucune anomalie'],CE15,159343,F,Lundi,09:30:00,['Aucune anomalie'],"['Manque séparation cabine/caisse', 'Véhicule ...",['Aucune anomalie']
1797,1798,2026-01-05 11:21:27,2026-01-05 11:24:30,2026-01-05 00:00:00,Agence / Antenne,DSP,Après chargement,REGION EST,NaN,NaN,...,True,['Aucune anomalie'],CE07,073869 MR2S,P,Lundi,11:30:00,['Colis en cabine'],['Etat général'],['Aucune anomalie']
1798,1799,2026-01-05 11:42:19,2026-01-05 11:46:00,2026-01-05 00:00:00,Agence / Antenne,DSP,Après chargement,REGION EST,NaN,NaN,...,True,['Aucune anomalie'],CE07,076968 let,C,Lundi,11:30:00,"['Colis en cabine', 'Autre']",['Clef laissé sur le contact'],['Aucune anomalie']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2225,2226,2026-03-31 15:11:43,2026-03-31 15:13:42,2026-03-25 00:00:00,Agence / Antenne,DSP,Après chargement,REGION NORD EST,NaN,NaN,...,True,['Aucune anomalie'],CE24,246724,B,Mardi,15:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
2226,2227,2026-03-31 15:13:44,2026-03-31 15:14:39,2026-03-25 00:00:00,Agence / Antenne,DSP,Après chargement,REGION NORD EST,NaN,NaN,...,True,['Aucune anomalie'],CE24,246768,E,Mardi,15:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
2227,2228,2026-03-31 15:14:41,2026-03-31 15:15:27,2026-03-25 00:00:00,Agence / Antenne,DSP,Après chargement,REGION NORD EST,NaN,NaN,...,True,['Aucune anomalie'],CE24,246768,F,Mardi,15:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
2228,2229,2026-03-31 15:15:28,2026-03-31 15:16:08,2026-03-25 00:00:00,Agence / Antenne,DSP,Après chargement,REGION NORD EST,NaN,NaN,...,True,['Aucune anomalie'],CE24,246768,H,Mardi,15:30:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
2229,2230,2026-03-31 15:21:24,2026-03-31 15:22:44,2026-03-31 00:00:00,Agence / Antenne,DSP,Après chargement,REGION IDF,NaN,NaN,...,True,['Aucune anomalie'],NaN,156001,D,Mardi,15:30:00,['Aucune anomalie'],['Véhicule vitré'],['Aucune anomalie']

In [13]:
df.sort_values(by="heure_de_debut")

,id,heure_de_debut,heure_de_fin,date,lieu_de_la_verification,appartenance_du_conducteur,type_de_verification,region,presence_licence_transport,numero_licence,...,is_surete,anomalie_suivi_de_tournee,agences_antennes,tournee,pda,jour,heure_arrondie,anomalie_list,anomalie_vehicule_list,anomalie_tournee_list
1794,1795,2026-01-02 12:49:58,2026-01-02 12:53:11,2026-01-02 00:00:00,Agence / Antenne,COLIS PRIVE,Après chargement,REGION EST,NaN,NaN,...,True,['Aucune anomalie'],CE28,148269 COLIS PRIVE,O,Vendredi,13:00:00,"['Colis en cabine', 'Adhésif Colis Privé dans ...",['Aucune anomalie'],['Aucune anomalie']
1795,1796,2026-01-05 09:34:22,2026-01-05 09:35:28,2026-01-05 00:00:00,Agence / Antenne,DSP,Après chargement,REGION NORD,NaN,NaN,...,True,['Aucune anomalie'],CE15,159561,I,Lundi,09:30:00,['Colis en cabine'],['Aucune anomalie'],['Aucune anomalie']
1796,1797,2026-01-05 09:35:29,2026-01-05 09:37:59,2026-01-05 00:00:00,Agence / Antenne,DSP,Après chargement,REGION NORD,NaN,NaN,...,True,['Aucune anomalie'],CE15,159343,F,Lundi,09:30:00,['Aucune anomalie'],"['Manque séparation cabine/caisse', 'Véhicule ...",['Aucune anomalie']
1797,1798,2026-01-05 11:21:27,2026-01-05 11:24:30,2026-01-05 00:00:00,Agence / Antenne,DSP,Après chargement,REGION EST,NaN,NaN,...,True,['Aucune anomalie'],CE07,073869 MR2S,P,Lundi,11:30:00,['Colis en cabine'],['Etat général'],['Aucune anomalie']
1798,1799,2026-01-05 11:42:19,2026-01-05 11:46:00,2026-01-05 00:00:00,Agence / Antenne,DSP,Après chargement,REGION EST,NaN,NaN,...,True,['Aucune anomalie'],CE07,076968 let,C,Lundi,11:30:00,"['Colis en cabine', 'Autre']",['Clef laissé sur le contact'],['Aucune anomalie']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2225,2226,2026-03-31 15:11:43,2026-03-31 15:13:42,2026-03-25 00:00:00,Agence / Antenne,DSP,Après chargement,REGION NORD EST,NaN,NaN,...,True,['Aucune anomalie'],CE24,246724,B,Mardi,15:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
2226,2227,2026-03-31 15:13:44,2026-03-31 15:14:39,2026-03-25 00:00:00,Agence / Antenne,DSP,Après chargement,REGION NORD EST,NaN,NaN,...,True,['Aucune anomalie'],CE24,246768,E,Mardi,15:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
2227,2228,2026-03-31 15:14:41,2026-03-31 15:15:27,2026-03-25 00:00:00,Agence / Antenne,DSP,Après chargement,REGION NORD EST,NaN,NaN,...,True,['Aucune anomalie'],CE24,246768,F,Mardi,15:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
2228,2229,2026-03-31 15:15:28,2026-03-31 15:16:08,2026-03-25 00:00:00,Agence / Antenne,DSP,Après chargement,REGION NORD EST,NaN,NaN,...,True,['Aucune anomalie'],CE24,246768,H,Mardi,15:30:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
2229,2230,2026-03-31 15:21:24,2026-03-31 15:22:44,2026-03-31 00:00:00,Agence / Antenne,DSP,Après chargement,REGION IDF,NaN,NaN,...,True,['Aucune anomalie'],NaN,156001,D,Mardi,15:30:00,['Aucune anomalie'],['Véhicule vitré'],['Aucune anomalie']

In [10]:
df2 = pd.read_excel('VERIFICATION DE CONCORDANCE DE CHARGEMENT VERIFICATION DOCUMENTAIRE - ETAT DES VEHICULES.xlsx')

In [11]:
df2

,ID,Heure de début,Heure de fin,Adresse de messagerie,Nom,Heure de la dernière modification,Date du contrôle,Personne en charge de la vérification,Lieu de la vérification,Appartenance du conducteur,...,Numéro de la licence,Présentation du Permis de Conduire\nHypothèse de la non présentation du permis de conduire : Contactez le gérant de l'entreprise de Transport afin de l'en informer.\nC'est à lui de gérer la situat...,Vérification Liste nominative des salariés affectés à la prestation\nLa personne en charge du contrôle à quai doit se munir de la liste nominative fournie par le gérant de l'entreprise de Transport...,ANOMALIE,ANOMALIE DE CHARGEMENT,Commentaires ( N° de colis...),ANOMALIE DE VEHICULE,Commentaires,Matière dangereuse,Commentaires divers
0,5001,2026-02-10 05:12:23,2026-02-10 05:14:39,anonymous,NaN,NaN,2026-02-06,EL OUARDI,Agence / Antenne,DSP,...,6,OUI,OUI,Non,NaN,NaN,NaN,NaN,NaN,RAS
1,5002,2026-02-10 07:38:26,2026-02-10 07:46:36,anonymous,NaN,NaN,2026-02-10,925683,Agence / Antenne,DSP,...,3,OUI,OUI,Oui,Colis non scanné (prévu pour ce chauffeur-livr...,510044192689/ 520044175008,NaN,2 Colis non scannés prévu s sur la tournée du ...,Conforme,Rappel procédure chargement / avertissement/ g...
2,5003,2026-02-10 07:50:26,2026-02-10 07:51:44,anonymous,NaN,NaN,2026-02-10,Nadia sayoudi,Agence / Antenne,DSP,...,2023/11/0002115,OUI,OUI,Non,NaN,NaN,NaN,NaN,NaN,NaN
3,5004,2026-02-10 07:53:16,2026-02-10 08:05:55,anonymous,NaN,NaN,2026-02-10,Cassandra,Agence / Antenne,DSP,...,2025/11/0002097,OUI,OUI,Oui,Colis non scanné (prévu pour ce chauffeur-livr...,Q42901578854,NaN,Colis en réceptionné,NaN,1 colis en Réceptionné
4,5005,2026-02-10 08:07:10,2026-02-10 08:08:32,anonymous,NaN,NaN,2026-02-10,Nadia sayoudi,Agence / Antenne,DSP,...,2023/11/0002115,OUI,OUI,Non,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2540,7541,2026-04-20 08:32:02,2026-04-20 08:34:07,anonymous,NaN,NaN,2026-04-20,TOURE Mohamed,Agence / Antenne,DSP,...,NaN,OUI,OUI,Non,NaN,NaN,NaN,NaN,NaN,RAS
2541,7542,2026-04-20 08:39:05,2026-04-20 08:40:53,anonymous,NaN,NaN,2026-04-20,927926,Agence / Antenne,DSP,...,0001,OUI,OUI,Oui,Colis en cabine;,NaN,NaN,NaN,NaN,NaN
2542,7543,2026-04-20 08:36:29,2026-04-20 09:02:07,anonymous,NaN,NaN,2026-04-20,Aurélia BOIS - Assistante Logistique,Agence / Antenne,DSP,...,2024/84/0000968 - 0010,OUI,OUI,Oui,NaN,NaN,Etat général;,Cabossé,NaN,RAS
2543,7544,2026-04-20 09:03:15,2026-04-20 09:16:29,anonymous,NaN,NaN,2026-04-20,Aurélia BOIS - Assistante Logistique,Agence / Antenne,DSP,...,2024/84/0000968 - 0062,OUI,OUI,Oui,Autre;,70 Colis à livrer mais que 67 chargés,NaN,NaN,NaN,À vérifier auprès des responsables
2544,7545,2026-04-20 09:16:33,2026-04-20 09:40:32,anonymous,NaN,NaN,2026-04-20,Aurélia BOIS - Assistante Logistique,Agence / Antenne,DSP,...,2024/84/0000968 - 0063,NON,OUI,Oui,NaN,NaN,Clef laissée sur le contact;,NaN,NaN,Pas de permis physique

In [20]:
df

,id,heure_de_debut,heure_de_fin,date,lieu_de_la_verification,appartenance_du_conducteur,type_de_verification,region,presence_licence_transport,numero_licence,...,is_surete,anomalie_suivi_de_tournee,agences_antennes,tournee,pda,jour,heure_arrondie,anomalie_list,anomalie_vehicule_list,anomalie_tournee_list
0,1,2025-03-14 09:07:53,2025-03-14 09:14:46,2025-03-14 00:00:00,Agence / Antenne,DSP,Après chargement,REGION EST,NaN,NaN,...,False,['Aucune anomalie'],AT7401,267408B,NaN,Vendredi,09:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
1,2,2025-03-14 09:14:49,2025-03-14 09:15:46,2025-03-14 00:00:00,Agence / Antenne,DSP,Avant chargement,REGION EST,NaN,NaN,...,False,['Aucune anomalie'],AT7401,267408C,NaN,Vendredi,09:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
2,3,2025-03-14 09:15:55,2025-03-14 09:16:48,2025-03-14 00:00:00,Agence / Antenne,DSP,Avant chargement,REGION EST,NaN,NaN,...,False,['Aucune anomalie'],AT7401,267408G,NaN,Vendredi,09:30:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
3,4,2025-03-14 09:06:36,2025-03-14 09:17:16,2025-03-14 00:00:00,Agence / Antenne,DSP,Avant chargement,REGION SUD,NaN,NaN,...,False,['Aucune anomalie'],CE05,053198 B AS LIVRAISON,NaN,Vendredi,09:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
4,5,2025-03-14 09:17:18,2025-03-14 09:18:56,2025-03-14 00:00:00,Agence / Antenne,DSP,Avant chargement,REGION SUD,NaN,NaN,...,False,['Aucune anomalie'],CE05,053198 D AS LIVRAISON,NaN,Vendredi,09:30:00,['Colis non scanné (prévu pour ce chauffeur-li...,['Aucune anomalie'],['Aucune anomalie']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4996,2026-02-09 12:28:37,2026-02-09 12:29:54,2026-02-09 00:00:00,Agence / Antenne,DSP,Après chargement,REGION OUEST,NON,NaN,...,False,['Aucune anomalie'],CE01,013578 KB TRANSPORT,PDA F,Lundi,12:30:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
4996,4997,2026-02-09 13:45:58,2026-02-09 13:49:23,2026-02-09 00:00:00,Agence / Antenne,COLIS PRIVE,Après chargement,REGION NORD,"Oui, licence de transport intérieur",217,...,False,['Aucune anomalie'],AT6001,156090,1,Lundi,14:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
4997,4998,2026-02-09 14:24:33,2026-02-09 14:28:05,2026-02-09 00:00:00,Délocalisé,DSP,Après chargement,REGION OUEST,"Oui, licence de transport intérieur",2024/52/0000020 copie 0002,...,False,['Aucune anomalie'],CE02,024490,A,Lundi,14:30:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
4998,4999,2026-02-09 13:06:10,2026-02-09 15:17:35,2026-02-13 00:00:00,Agence / Antenne,DSP,Après chargement,REGION EST,"Oui, licence de transport intérieur",172,...,False,['Aucune anomalie'],CE28,286933,D,Lundi,13:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
4999,5000,2026-02-09 15:17:37,2026-02-09 16:08:45,2026-02-03 00:00:00,Agence / Antenne,DSP,Après chargement,REGION EST,"Oui, licence de transport intérieur",927,...,False,['Aucune anomalie'],CE28,286961,286961D,Lundi,15:30:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']

In [15]:
df

,id,heure_de_debut,heure_de_fin,date,lieu_de_la_verification,appartenance_du_conducteur,type_de_verification,region,presence_licence_transport,numero_licence,...,is_surete,anomalie_suivi_de_tournee,agences_antennes,tournee,pda,jour,heure_arrondie,anomalie_list,anomalie_vehicule_list,anomalie_tournee_list
19,20,2025-03-17 07:34:32,2025-03-17 07:54:10,2025-03-17 00:00:00,Agence / Antenne,COLIS PRIVE,Avant chargement,REGION OUEST,NaN,NaN,...,False,['Aucune anomalie'],NaN,7910,NaN,Lundi,07:30:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
70,71,2025-03-21 08:46:35,2025-03-21 08:47:26,2025-03-18 00:00:00,Agence / Antenne,DSP,Après chargement,REGION OUEST,NaN,NaN,...,False,['Aucune anomalie'],NaN,169145B,NaN,Vendredi,09:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
71,72,2025-03-21 08:47:31,2025-03-21 08:48:06,2025-03-18 00:00:00,Agence / Antenne,DSP,Après chargement,REGION OUEST,NaN,NaN,...,False,['Aucune anomalie'],NaN,169146B,NaN,Vendredi,09:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
77,78,2025-03-21 11:00:07,2025-03-21 11:04:16,2025-03-21 00:00:00,Agence / Antenne,COLIS PRIVE,Avant chargement,REGION SUD,NaN,0135,...,False,['Aucune anomalie'],NaN,088430M,NaN,Vendredi,11:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
234,235,2025-04-09 09:19:21,2025-04-09 10:36:49,2025-04-09 00:00:00,Agence / Antenne,DSP,Avant chargement,REGION OUEST,NaN,6,...,False,['Aucune anomalie'],NaN,277638G,NaN,Mercredi,09:30:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
374,375,2025-04-24 08:52:18,2025-04-24 08:54:07,2025-04-24 00:00:00,Agence / Antenne,DSP,Avant chargement,REGION OUEST,NaN,NaN,...,False,['Aucune anomalie'],NaN,7979,NaN,Jeudi,09:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
468,469,2025-04-30 10:11:20,2025-04-30 10:13:18,2025-04-30 00:00:00,Délocalisé,DSP,Après chargement,REGION EST,NaN,2021/32/0001101,...,False,['Aucune anomalie'],NaN,106213 b jerome derollez,NaN,Mercredi,10:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
503,504,2025-05-02 11:11:07,2025-05-02 11:25:58,2025-05-02 00:00:00,Agence / Antenne,DSP,Avant chargement,REGION SUD,NaN,0007,...,False,['Aucune anomalie'],NaN,PDA D RK transport,NaN,Vendredi,11:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
538,539,2025-05-05 10:59:34,2025-05-05 11:22:06,2025-05-05 00:00:00,Agence / Antenne,COLIS PRIVE,Avant chargement,REGION SUD,NaN,2025/93/0000131,...,False,['Aucune anomalie'],NaN,0884300,NaN,Lundi,11:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
577,578,2025-05-09 08:13:11,2025-05-09 08:15:59,2025-05-09 00:00:00,Agence / Antenne,DSP,Avant chargement,REGION SUD,NaN,2014/75/0000375,...,False,['Aucune anomalie'],NaN,043397,NaN,Vendredi,08:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
664,665,2025-05-15 09:54:42,2025-05-15 10:00:48,2025-05-15 00:00:00,Agence / Antenne,DSP,Après chargement,REGION NORD,NaN,0003,...,False,['Aucune anomalie'],NaN,156010/A /Bilik Services,NaN,Jeudi,10:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
865,866,2025-05-31 11:29:11,2025-05-31 11:30:38,2025-05-31 00:00:00,Agence / Antenne,COLIS PRIVE,Après chargement,REGION NORD,NaN,216,...,False,['Aucune anomalie'],NaN,156088T,NaN,Samedi,11:30:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
866,867,2025-05-31 11:44:59,2025-05-31 11:45:24,2025-05-31 00:00:00,Agence / Antenne,COLIS PRIVE,Après chargement,REGION NORD,NaN,Pas de licence,...,False,['Aucune anomalie'],NaN,156088A,NaN,Samedi,11:30:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
967,968,2025-06-10 12:11:42,2025-06-10 12:15:04,2025-06-10 00:00:00,Agence / Antenne,COLIS PRIVE,Avant chargement,REGION SUD,NaN,2025/93/00001,...,False,['Aucune anomalie'],NaN,088430M,NaN,Mardi,12:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
1193,1194,2025-06-26 11:34:39,2025-06-26 11:38:47,2025-06-26 00:00:00,Agence / Antenne,COLIS PRIVE,Avant chargement,REGION SUD,NaN,0128,...,False,['Aucune anomalie'],NaN,088430B,NaN,Jeudi,11:30:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
1360,1361,2025-07-07 08:32:05,2025-07-07 08:34:03,2025-07-03 00:00:00,Agence / Antenne,DSP,Après chargement,REGION EST,NaN,NaN,...,False,['Aucune anomalie'],NaN,246724/ PDA D / S.H TRANSPORT,NaN,Lundi,08:30:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
1445,1446,2025-07-12 09:43:59,2025-07-12 09:48:47,2025-07-12 00:00:00,Agence / Antenne,COLIS PRIVE,Après chargement,REGION EST,NaN,153,...,False,['Aucune anomalie'],NaN,091930/2,NaN,Samedi,09:30:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
1446,1447,2025-07-12 09:49:04,2025-07-12 09:52:52,2025-07-12 00:00:00,Agence / Antenne,COLIS PRIVE,Après chargement,REGION EST,NaN,157,...,False,['Aucune anomalie'],NaN,091930/9,NaN,Samedi,10:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
1471,1472,2025-07-15 10:37:40,2025-07-15 10:39:38,2025-07-15 00:00:00,Agence / Antenne,COLIS PRIVE,Après chargement,REGION OUEST,NaN,011,...,False,['Aucune anomalie'],NaN,012249/D/CPL,NaN,Mardi,10:30:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
1568,1569,2025-07-21 10:51:35,2025-07-21 10:54:19,2025-07-21 00:00:00,Agence / Antenne,COLIS PRIVE,Avant chargement,REGION SUD,NaN,0131,...,False,['Aucune anomalie'],NaN,30300010,NaN,Lundi,11:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
1794,1795,2025-08-02 09:57:54,2025-08-02 10:00:28,2025-08-02 00:00:00,Agence / Antenne,COLIS PRIVE,Après chargement,REGION EST,NaN,153,...,False,['Aucune anomalie'],NaN,091930 / 3,NaN,Samedi,10:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
1810,1811,2025-08-04 10:33:04,2025-08-04 10:36:50,2025-08-04 00:00:00,Agence / Antenne,COLIS PRIVE,Avant chargement,REGION EST,NaN,270,...,False,['Aucune anomalie'],NaN,284283 PDA U,NaN,Lundi,10:30:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
1907,1908,2025-08-11 12:54:09,2025-08-11 12:55:55,2025-08-11 00:00:00,Agence / Antenne,COLIS PRIVE,Avant chargement,REGION OUEST,NaN,0004,...,False,['Aucune anomalie'],NaN,012966/B FABIEN,NaN,Lundi,13:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
2162,2163,2025-09-05 11:41:01,2025-09-05 11:44:47,2025-09-05 00:00:00,Agence / Antenne,DSP,Après chargement,REGION OUEST,NaN,2024/11/0001218 N*2,...,False,['Aucune anomalie'],NaN,013578 PDA D KB TRANSPORT,NaN,Vendredi,11:30:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
2163,2164,2025-09-05 11:44:54,2025-09-05 11:46:57,2025-09-05 00:00:00,Agence / Antenne,DSP,Après chargement,REGION OUEST,NaN,NaN,...,False,['Aucune anomalie'],NaN,013578 PDA B KBTRANSPORT,NaN,Vendredi,11:30:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
2572,2573,2025-10-08 10:35:08,2025-10-08 10:50:39,2025-10-08 00:00:00,Agence / Antenne,DSP,Après chargement,REGION SUD,NaN,NaN,...,False,['Aucune anomalie'],NaN,043308c,NaN,Mercredi,10:30:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
2739,2740,2025-10-15 11:47:14,2025-10-15 11:50:44,2025-10-15 00:00:00,Agence / Antenne,COLIS PRIVE,Avant chargement,REGION OUEST,NaN,396,...,False,['Aucune anomalie'],NaN,F-1476867,NaN,Mercredi,12:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
3426,3427,2025-11-15 11:25:50,2025-11-15 11:27:38,2025-11-15 00:00:00,Agence / Antenne,COLIS PRIVE,Avant chargement,REGION OUEST,NaN,459,...,False,['Aucune anomalie'],NaN,K-1450513,NaN,Samedi,11:30:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
3559,3560,2025-11-22 12:14:56,2025-11-22 12:18:04,2025-11-22 00:00:00,Agence / Antenne,COLIS PRIVE,Avant chargement,REGION OUEST,NaN,457,...,False,['Aucune anomalie'],NaN,Z-1478635,NaN,Samedi,12:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
3593,3594,2025-11-25 14:14:51,2025-11-25 14:17:09,2025-11-25 00:00:00,Agence / Antenne,COLIS PRIVE,Avant chargement,REGION OUEST,NaN,15,...,False,['Aucune anomalie'],NaN,C-1476860,NaN,Mardi,14:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
3633,3634,2025-11-27 11:57:48,2025-11-27 12:00:11,2025-11-27 00:00:00,Agence / Antenne,COLIS PRIVE,Avant chargement,REGION OUEST,NaN,522,...,False,['Aucune anomalie'],NaN,E-1456270,NaN,Jeudi,12:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
3879,3880,2025-12-12 11:45:50,2025-12-12 11:51:31,2025-12-12 00:00:00,Agence / Antenne,COLIS PRIVE,Avant chargement,REGION OUEST,NaN,10,...,False,['Aucune anomalie'],NaN,W-1484675,NaN,Vendredi,12:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
3918,3919,2025-12-16 11:34:37,2025-12-16 11:45:59,2025-12-16 00:00:00,Agence / Antenne,DSP,Avant chargement,REGION OUEST,NaN,0008,...,False,['Aucune anomalie'],NaN,088403J,NaN,Mardi,11:30:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
4008,4009,2025-12-18 15:10:19,2025-12-18 15:15:37,2025-12-18 00:00:00,Délocalisé,DSP,Après chargement,REGION OUEST,NaN,2025/52/0000255,...,False,['Aucune anomalie'],NaN,024465 b delivery express,NaN,Jeudi,15:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
4060,4061,2025-12-20 11:16:36,2025-12-20 11:21:50,2025-12-20 00:00:00,Agence / Antenne,COLIS PRIVE,Avant chargement,REGION SUD,NaN,0483,...,False,['Aucune anomalie'],NaN,088431T,NaN,Samedi,11:30:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
4155,4156,2025-12-26 11:22:35,2025-12-26 11:30:15,2025-12-26 00:00:00,Agence / Antenne,DSP,Avant chargement,REGION OUEST,NaN,14,...,False,['Aucune anomalie'],NaN,1468615,H,Vendredi,11:30:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
4325,4326,2026-01-08 13:28:00,2026-01-08 13:29:35,2026-01-08 00:00:00,Agence / Antenne,COLIS PRIVE,Avant chargement,REGION OUEST,NaN,522,...,False,['Aucune anomalie'],NaN,1456270,E,Jeudi,13:30:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
4382,4383,2026-01-13 09:22:13,2026-01-13 09:26:36,2026-01-13 00:00:00,Agence / Antenne,DSP,Après chargement,REGION NORD,NaN,9,...,False,['Aucune anomalie'],NaN,177773,C,Mardi,09:30:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
4389,4390,2026-01-13 11:08:30,2026-01-13 11:10:38,2026-01-13 00:00:00,Agence / Antenne,DSP,Avant chargement,REGION SUD,NaN,1,...,False,['Aucune anomalie'],NaN,089993,a,Mardi,11:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
4616,4617,2026-01-23 11:53:58,2026-01-23 11:55:30,2026-01-23 00:00:00,Agence / Antenne,COLIS PRIVE,Avant chargement,REGION OUEST,NaN,456,...,False,['Aucune anomalie'],NaN,1476863,N,Vendredi,12:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
4618,4619,2026-01-23 11:55:32,2026-01-23 11:56:40,2026-01-23 00:00:00,Agence / Antenne,COLIS PRIVE,Avant chargement,REGION OUEST,NaN,13,...,False,['Aucune anomalie'],NaN,1484467,Yass2,Vendredi,12:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
4674,4675,2026-01-27 11:49:24,2026-01-27 11:54:56,2026-01-27 00:00:00,Agence / Antenne,COLIS PRIVE,Avant chargement,REGION OUEST,NaN,455,...,False,['Aucune anomalie'],NaN,1476868,M,Mardi,12:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
5021,5022,2026-01-12 10:47:25,2026-01-12 10:55:16,2026-01-12 00:00:00,Agence / Antenne,DSP,Avant chargement,REGION SUD,NaN,NaN,...,True,['Aucune anomalie'],NaN,19,B,Lundi,11:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
5152,5153,2026-02-13 11:16:12,2026-02-13 11:17:16,2026-02-13 00:00:00,Agence / Antenne,DSP,Après chargement,REGION SUD EST,NaN,NaN,...,True,['Aucune anomalie'],NaN,088314,B,Vendredi,11:30:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']

In [10]:
df[df["is_surete"] == True]

,id,heure_de_debut,heure_de_fin,date,lieu_de_la_verification,appartenance_du_conducteur,type_de_verification,region,presence_licence_transport,numero_licence,...,is_surete,anomalie_suivi_de_tournee,agences_antennes,tournee,pda,jour,heure_arrondie,anomalie_list,anomalie_vehicule_list,anomalie_tournee_list
5021,5022,2026-01-12 10:47:25,2026-01-12 10:55:16,2026-01-12 00:00:00,Agence / Antenne,DSP,Avant chargement,REGION SUD,NaN,NaN,...,True,['Aucune anomalie'],NaN,19,B,Lundi,11:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
5152,5153,2026-02-13 11:16:12,2026-02-13 11:17:16,2026-02-13 00:00:00,Agence / Antenne,DSP,Après chargement,REGION SUD EST,NaN,NaN,...,True,['Aucune anomalie'],NaN,088314,B,Vendredi,11:30:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']

In [4]:
df.columns

Index(['id', 'heure_de_debut', 'heure_de_fin', 'date',
       'lieu_de_la_verification', 'appartenance_du_conducteur',
       'type_de_verification', 'region', 'presence_licence_transport',
       'numero_licence', 'presentation_permis_conduire',
       'verification_liste_nominative', 'anomalie', 'anomalie_de_chargement',
       'anomalie_de_vehicule', 'is_surete', 'anomalie_suivi_de_tournee',
       'agences_antennes', 'tournee', 'pda', 'jour', 'heure_arrondie',
       'anomalie_list', 'anomalie_vehicule_list', 'anomalie_tournee_list'],
      dtype='object')

In [12]:
# Charger les fichiers Excel
df1 = pd.read_excel("VERIFICATION DE CONCORDANCE DE CHARGEMENT VERIFICATION DOCUMENTAIRE - ETAT DES VEHICULES.xlsx", engine="openpyxl")
df2 = pd.read_excel("SURETE - VERIFICATION DE CONCORDANCE DE CHARGEMENT 2026.xlsx", engine="openpyxl", skiprows=[1, 1])

In [98]:
# Étape 1 : Renommer les colonnes du premier DataFrame pour correspondre au second
rename_dict = {
    'Date du contrôle': 'Date',
    'Personne en charge de la vérification': 'Nom de la personne en charge de la vérification',
    'Tournée / PDA / Nom de la société si besoin': 'Tournée / PDA / Nom de la société si DSP',
    'Type de véhicule / Immatriculation': 'Type de véhicule / immatriculation',
    'N° TOURNEE' : 'NUMERO DE TOURNEE'
}
df1 = df1.rename(columns=rename_dict)

In [13]:
set(df1.columns)

{'AGENCES/ ANTENNES REGION SUD EST',
 'AGENCES/ANTENNES REGION IDF',
 'AGENCES/ANTENNES REGION NORD EST',
 'AGENCES/ANTENNES REGION NORD OUEST',
 'AGENCES/ANTENNES REGION SUD OUEST',
 'ANOMALIE',
 'ANOMALIE DE CHARGEMENT\xa0',
 'ANOMALIE DE VEHICULE',
 'Adresse de messagerie',
 'Appartenance du conducteur',
 'Commentaires',
 'Commentaires ( N° de colis...)',
 'Commentaires divers\xa0',
 'Date du contrôle',
 'Heure de début',
 'Heure de fin',
 'Heure de la dernière modification',
 'ID',
 'Immatriculation',
 'LETTRE DE PDA',
 'Lieu de la vérification',
 'Matière dangereuse',
 'Nom',
 'Numéro de la licence',
 'N° TOURNEE',
 'Personne en charge de la vérification',
 "Présence dans le véhicule de la copie numérotée de la licence de transport.\xa0\nHypothèse de la non présentation : Contactez le\xa0gérant de l'entreprise de Transport afin de l'en informer.\xa0\nC'est à lui...",
 "Présentation du Permis de Conduire\nHypothèse de la non présentation du permis de conduire :\xa0 Contactez le\xa0gérant de l'entreprise de Transport\xa0\xa0afin de l'en informer.\nC'est à lui de gérer\xa0la situat...",
 'REGION',
 'Type de vérification',
 "Vérification Liste nominative des salariés affectés à la prestation\nLa personne en charge du contrôle à quai doit se munir de la liste nominative fournie par le gérant de l'entreprise de Transport..."}

In [100]:
set(df2.columns)

{'AGENCES/ ANTENNES REGION EST',
 'AGENCES/ANTENNES REGION NORD',
 'AGENCES/ANTENNES REGION OUEST',
 'AGENCES/ANTENNES REGION SUD',
 'ANOMALIE',
 'ANOMALIE DE CHARGEMENT\xa0',
 'ANOMALIE DE VEHICULE',
 'ANOMALIE SUIVI DE TOURNEE',
 'Adresse de messagerie',
 'Appartenance du conducteur',
 'Commentaires',
 'Commentaires ( N° de colis...)',
 'Commentaires divers\xa0',
 'Date',
 'Heure de début',
 'Heure de fin',
 'Id',
 'Immatriculation',
 'LETTRE DE PDA',
 'Lieu de la vérification',
 'Matière dangereuse',
 'NUMERO DE TOURNEE',
 'Nom',
 'Nom de la personne en charge de la vérification',
 'REGION',
 'Type de vérification'}

In [101]:
# Étape 2 : Ajouter la colonne 'is_surete'
df1['is_surete'] = False
df2['is_surete'] = True

In [102]:
# Étape 3 : Supprimer la colonne 'id' ou 'Id' des deux DataFrames pour éviter les doublons
for df in [df1, df2]:
    if 'Id' in df.columns:
        df.drop(columns=['Id'], inplace=True)
    if 'id' in df.columns:
        df.drop(columns=['id'], inplace=True)

# Étape 4 : Concaténer les deux DataFrames
df_combined = pd.concat([df1, df2], ignore_index=True)

# Étape 5 : Générer une nouvelle colonne 'id' avec des valeurs uniques
df_combined['id'] = range(1, len(df_combined) + 1)

In [103]:
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5539 entries, 0 to 5538
Data columns (total 31 columns):
 #   Column                                                                                                                                                                                                    Non-Null Count  Dtype
---  ------                                                                                                                                                                                                    --------------  -----
 0   Heure de début                                                                                                                                                                                            5539 non-null   datetime64[ns]
 1   Heure de fin                                                                                                                                                                                              5539 non-null   datetime64[ns]
 2   Adresse de messagerie                                                                                                                                                                                     5539 non-null   object
 3   Nom                                                                                                                                                                                                       840 non-null    object
 4   Date                                                                                                                                                                                                      5539 non-null   datetime64[ns]
 5   Nom de la personne en charge de la vérification                                                                                                                                                           5539 non-null   object
 6   Lieu de la vérification                                                                                                                                                                                   5539 non-null   object
 7   Appartenance du conducteur                                                                                                                                                                                5539 non-null   object
 8   NUMERO DE TOURNEE                                                                                                                                                                                         5539 non-null   object
 9   LETTRE DE PDA                                                                                                                                                                                             635 non-null    object
 10  Immatriculation                                                                                                                                                                                           5539 non-null   object
 11  Type de vérification                                                                                                                                                                                      5539 non-null   object
 12  REGION                                                                                                                                                                                                    5539 non-null   object
 13  AGENCES/ ANTENNES REGION EST                                                                                                                                                                              982 non-null    object
 14  AGENCES/ANTENNES REGION NORD                                                                                                                                                                              1200 non-null   object
 15  AGENCES/ANTENNES REGION OUEST                                                                                                                                                                             1948 non-null   object
 16  AGENCES/ANTENNES REGION SUD                                                                                                                                                                               1367 non-null   object
 17  Présence dans le véhicule de la copie numérotée de la licence de transport.
Hypothèse de la non présentation : Contactez le gérant de l'entreprise de Transport afin de l'en informer.
C'est à lui de   4664 non-null   object
 18  Numéro de la licence                                                                                                                                                                                      4312 non-null   object
 19  Présentation du Permis de Conduire
Hypothèse de la non présentation du permis de conduire :  Contactez le gérant de l'entreprise de Transport  afin de l'en informer.
C'est à lui de gérer la situation.  4642 non-null   object
 20  Vérification Liste nominative des salariés affectés à la prestation
La personne en charge du contrôle à quai doit se munir de la liste nominative fournie par le gérant de l'entreprise de Transport et   4559 non-null   object
 21  ANOMALIE                                                                                                                                                                                                  5539 non-null   object
 22  ANOMALIE DE CHARGEMENT                                                                                                                                                                                    907 non-null    object
 23  Commentaires ( N° de colis...)                                                                                                                                                                            302 non-null    object
 24  ANOMALIE DE VEHICULE                                                                                                                                                                                      127 non-null    object
 25  Commentaires                                                                                                                                                                                              126 non-null    object
 26  Matière dangereuse                                                                                                                                                                                        38 non-null     object
 27  Commentaires divers                                                                                                                                                                                       2840 non-null   object
 28  is_surete                                                                                                                                                                                                 5539 non-null   bool
 29  ANOMALIE SUIVI DE TOURNEE                                                                                                                                                                                 15 non-null     object
 30  id                                                                                                                                                                                                        5539 non-null   int64
dtypes: bool(1), datetime64[ns](3), int64(1), object(26)
memory usage: 1.3+ MB

In [104]:
set(df_combined.columns)

{'AGENCES/ ANTENNES REGION EST',
 'AGENCES/ANTENNES REGION NORD',
 'AGENCES/ANTENNES REGION OUEST',
 'AGENCES/ANTENNES REGION SUD',
 'ANOMALIE',
 'ANOMALIE DE CHARGEMENT\xa0',
 'ANOMALIE DE VEHICULE',
 'ANOMALIE SUIVI DE TOURNEE',
 'Adresse de messagerie',
 'Appartenance du conducteur',
 'Commentaires',
 'Commentaires ( N° de colis...)',
 'Commentaires divers\xa0',
 'Date',
 'Heure de début',
 'Heure de fin',
 'Immatriculation',
 'LETTRE DE PDA',
 'Lieu de la vérification',
 'Matière dangereuse',
 'NUMERO DE TOURNEE',
 'Nom',
 'Nom de la personne en charge de la vérification',
 'Numéro de la licence',
 "Présence dans le véhicule de la copie numérotée de la licence de transport.\xa0\nHypothèse de la non présentation : Contactez le\xa0gérant de l'entreprise de Transport afin de l'en informer.\xa0\nC'est à lui de ",
 "Présentation du Permis de Conduire\nHypothèse de la non présentation du permis de conduire :\xa0 Contactez le\xa0gérant de l'entreprise de Transport\xa0\xa0afin de l'en informer.\nC'est à lui de gérer\xa0la situation.",
 'REGION',
 'Type de vérification',
 "Vérification Liste nominative des salariés affectés à la prestation\nLa personne en charge du contrôle à quai doit se munir de la liste nominative fournie par le gérant de l'entreprise de Transport et ",
 'id',
 'is_surete'}

In [105]:
def extract_vehicle_info(value):
    if pd.isna(value):
        return pd.NA, pd.NA
    
    # Convertir en majuscule pour homogénéité
    value = str(value).upper().strip()
    
    # Expression régulière pour détecter les immatriculations (format XX-123-YY ou similaire)
    immat_pattern = r'[A-Z]{1,2}-?\d{2,3}-?[A-Z]{1,2}|[A-Z]{1,2}\d{2,3}[A-Z]{1,2}'
    
    # Chercher l'immatriculation dans la valeur
    immat_match = re.search(immat_pattern, value.replace(" ", ""))
    
    if immat_match:
        immat = immat_match.group(0)
        # Standardiser le format de l'immatriculation (ajouter des tirets si nécessaire)
        immat = immat.replace("-", "")  # Supprimer les tirets existants
        if len(immat) >= 5:  # Vérifier que l'immatriculation a assez de caractères
            immat_standard = f"{immat[:2]}-{immat[2:-2]}-{immat[-2:]}"
        else:
            immat_standard = immat
        
        # Extraire le type de véhicule (tout ce qui est avant l'immatriculation)
        type_vehicule = value.replace(immat_match.group(0), "").strip().replace("/", "").strip()
        if not type_vehicule:  # Si vide, assigner "INCONNU"
            type_vehicule = "INCONNU"
    else:
        # Si aucune immatriculation n'est trouvée, toute la valeur est le type de véhicule
        type_vehicule = value
        immat_standard = pd.NA
    
    return type_vehicule, immat_standard


def arrondir_demi_heure(dt):
    minute = dt.minute
    if minute < 15:
        minute = 0
    elif minute < 45:
        minute = 30
    else:
        dt += pd.Timedelta(hours=1)
        minute = 0
    return dt.replace(minute=minute, second=0, microsecond=0)


def rename_columns(df):
    """
    Renomme les colonnes d'un DataFrame pour correspondre à la table SQL verifications_chargement.
    Les noms sont convertis en snake_case et les colonnes longues sont raccourcies.
    
    Args:
        df (pd.DataFrame): DataFrame contenant les données brutes (par exemple, issues d'un fichier Excel).
    
    Returns:
        pd.DataFrame: DataFrame avec les colonnes renommées.
    """
    # Dictionnaire de mappage des noms de colonnes originaux vers les noms cibles
    column_mapping = {
        'Id': 'id',
        'Heure de début': 'heure_de_debut',
        'Heure de fin': 'heure_de_fin',
        'Date': 'date',
        'Lieu de la vérification': 'lieu_de_la_verification',
        'Appartenance du conducteur': 'appartenance_du_conducteur',
        'Type de vérification': 'type_de_verification',
        'REGION': 'region',
        "Présence dans le véhicule de la copie numérotée de la licence de transport.\xa0\nHypothèse de la non présentation : Contactez le\xa0gérant de l'entreprise de Transport afin de l'en informer.\xa0\nC'est à lui de " : 'presence_licence_transport',
        'Numéro de la licence': 'numero_licence',
        "Présentation du Permis de Conduire\nHypothèse de la non présentation du permis de conduire :\xa0 Contactez le\xa0gérant de l'entreprise de Transport\xa0\xa0afin de l'en informer.\nC'est à lui de gérer\xa0la situation." : 'presentation_permis_conduire',
        "Vérification Liste nominative des salariés affectés à la prestation\nLa personne en charge du contrôle à quai doit se munir de la liste nominative fournie par le gérant de l'entreprise de Transport et " : 'verification_liste_nominative',
        'ANOMALIE': 'anomalie',
        'ANOMALIE DE CHARGEMENT': 'anomalie_de_chargement',
        'ANOMALIE DE VEHICULE': 'anomalie_de_vehicule',
        'ANOMALIE SUIVI DE TOURNEE': 'anomalie_suivi_de_tournee',
        'AGENCES/ANTENNES': 'agences_antennes',
        'NUMERO DE TOURNEE': 'tournee',
        'LETTRE DE PDA': 'pda',
        'jour': 'jour',
        'heure_arrondie': 'heure_arrondie',
        'is_surete': 'is_surete'
    }

    # Nettoyer les noms de colonnes du DataFrame (supprimer \xa0, \n, espaces multiples)
    df.columns = [re.sub(r'\s+', ' ', col.replace('\xa0', ' ').replace('\n', ' ').strip()) for col in df.columns]

    # Créer un dictionnaire de mappage actualisé en tenant compte des colonnes nettoyées
    cleaned_mapping = {}
    for original_col, new_col in column_mapping.items():
        cleaned_col = re.sub(r'\s+', ' ', original_col.replace('\xa0', ' ').replace('\n', ' ').strip())
        cleaned_mapping[cleaned_col] = new_col

    # Vérifier les colonnes manquantes
    missing_cols = [col for col in cleaned_mapping.values() if col not in df.columns]
    if missing_cols:
        print(f"Avertissement : Les colonnes suivantes sont attendues mais absentes dans le DataFrame : {missing_cols}")

    # Renommer les colonnes
    df = df.rename(columns=cleaned_mapping)

    # Vérifier que toutes les colonnes cibles sont présentes, sinon ajouter des colonnes vides
    target_columns = [
        'id', 'heure_de_debut', 'heure_de_fin', 'date', 'lieu_de_la_verification',
        'appartenance_du_conducteur', 'type_de_verification',
        'region', 'presence_licence_transport', 'numero_licence', 'presentation_permis_conduire',
        'verification_liste_nominative', 'anomalie', 'anomalie_de_chargement',
        'anomalie_de_vehicule', 'is_surete', 'anomalie_suivi_de_tournee',
        'agences_antennes', 'tournee', 'pda', 'jour', 'heure_arrondie'
    ]
    for col in target_columns:
        if col not in df.columns:
            df[col] = pd.NA
            print(f"Colonne '{col}' ajoutée avec des valeurs NULL car absente du DataFrame.")

    # Réorganiser les colonnes pour correspondre à l'ordre de la table SQL
    df = df[target_columns]

    return df

def preprocessing(df):
    df["AGENCES/ANTENNES"] = ""
    for index, row in df.iterrows():
        if row["REGION"] == "REGION EST":
            df.at[index, "AGENCES/ANTENNES"] = row["AGENCES/ ANTENNES REGION EST"]
        elif row["REGION"] == "REGION NORD":
            df.at[index, "AGENCES/ANTENNES"] = row["AGENCES/ANTENNES REGION NORD"]
        elif row["REGION"] == "REGION OUEST":
            df.at[index, "AGENCES/ANTENNES"] = row["AGENCES/ANTENNES REGION OUEST"]
        elif row["REGION"] == "REGION SUD":
            df.at[index, "AGENCES/ANTENNES"] = row["AGENCES/ANTENNES REGION SUD"]
    
    # Supprimer les colonnes inutiles
    df = df.drop(columns=["AGENCES/ ANTENNES REGION EST", "AGENCES/ANTENNES REGION NORD", 
                          "AGENCES/ANTENNES REGION OUEST", "AGENCES/ANTENNES REGION SUD"])

    df["Nom"] = df["Nom"].str.upper()
    df["Nom"] = df["Nom"].str.replace("-", " ", regex=False)

    # Appliquer la fonction pour créer deux nouvelles colonnes
    df[["Type de véhicule", "Immatriculation"]] = df["Immatriculation"].apply(
        lambda x: pd.Series(extract_vehicle_info(x))
    )
    
    # Mettre les colonnes en majuscule pour homogénéité
    df["Type de véhicule"] = df["Type de véhicule"].str.upper()
    df["Immatriculation"] = df["Immatriculation"].str.upper()

    
    
    # Standardiser : tout en majuscule
    df["PDA"] = df["LETTRE DE PDA"].str.upper()
    
    df.drop(columns=["Matière dangereuse"],inplace=True)
    df.rename(columns={"ANOMALIE DE CHARGEMENT\xa0":"ANOMALIE DE CHARGEMENT"},inplace = True)
    df.rename(columns={"Commentaires divers\xa0":"Commentaires divers"},inplace = True)

    df.drop(columns =["Adresse de messagerie", "Nom", "Nom de la personne en charge de la vérification", "Commentaires ( N° de colis...)", "Commentaires", "Commentaires divers", "Type de véhicule", "Immatriculation" ],inplace=True)

    df["Heure de début"] = pd.to_datetime(df["Heure de début"])
    df["Heure de fin"] = pd.to_datetime(df["Heure de fin"])
    df["Date"] = pd.to_datetime(df["Date"])

    df["jour"] = df["Heure de début"].dt.day_name(locale='fr_FR')

    df["heure_arrondie"] = df["Heure de début"].apply(arrondir_demi_heure).dt.time

    df = rename_columns(df)

    df["appartenance_du_conducteur"] = df["appartenance_du_conducteur"].replace({"COLIS PRIVE LIVRAISON": "COLIS PRIVE"})
    

    return df

In [106]:
# Appliquer le preprocessing
df = preprocessing(df_combined)

Avertissement : Les colonnes suivantes sont attendues mais absentes dans le DataFrame : ['heure_de_debut', 'heure_de_fin', 'date', 'lieu_de_la_verification', 'appartenance_du_conducteur', 'type_de_verification', 'region', 'presence_licence_transport', 'numero_licence', 'presentation_permis_conduire', 'verification_liste_nominative', 'anomalie', 'anomalie_de_chargement', 'anomalie_de_vehicule', 'anomalie_suivi_de_tournee', 'agences_antennes', 'tournee', 'pda']

In [107]:
set(df_combined.columns)

{'AGENCES/ ANTENNES REGION EST',
 'AGENCES/ANTENNES',
 'AGENCES/ANTENNES REGION NORD',
 'AGENCES/ANTENNES REGION OUEST',
 'AGENCES/ANTENNES REGION SUD',
 'ANOMALIE',
 'ANOMALIE DE CHARGEMENT\xa0',
 'ANOMALIE DE VEHICULE',
 'ANOMALIE SUIVI DE TOURNEE',
 'Adresse de messagerie',
 'Appartenance du conducteur',
 'Commentaires',
 'Commentaires ( N° de colis...)',
 'Commentaires divers\xa0',
 'Date',
 'Heure de début',
 'Heure de fin',
 'Immatriculation',
 'LETTRE DE PDA',
 'Lieu de la vérification',
 'Matière dangereuse',
 'NUMERO DE TOURNEE',
 'Nom',
 'Nom de la personne en charge de la vérification',
 'Numéro de la licence',
 "Présence dans le véhicule de la copie numérotée de la licence de transport.\xa0\nHypothèse de la non présentation : Contactez le\xa0gérant de l'entreprise de Transport afin de l'en informer.\xa0\nC'est à lui de ",
 "Présentation du Permis de Conduire\nHypothèse de la non présentation du permis de conduire :\xa0 Contactez le\xa0gérant de l'entreprise de Transport\xa0\xa0afin de l'en informer.\nC'est à lui de gérer\xa0la situation.",
 'REGION',
 'Type de vérification',
 "Vérification Liste nominative des salariés affectés à la prestation\nLa personne en charge du contrôle à quai doit se munir de la liste nominative fournie par le gérant de l'entreprise de Transport et ",
 'id',
 'is_surete'}

In [108]:
set(df.columns)

{'agences_antennes',
 'anomalie',
 'anomalie_de_chargement',
 'anomalie_de_vehicule',
 'anomalie_suivi_de_tournee',
 'appartenance_du_conducteur',
 'date',
 'heure_arrondie',
 'heure_de_debut',
 'heure_de_fin',
 'id',
 'is_surete',
 'jour',
 'lieu_de_la_verification',
 'numero_licence',
 'pda',
 'presence_licence_transport',
 'presentation_permis_conduire',
 'region',
 'tournee',
 'type_de_verification',
 'verification_liste_nominative'}

In [109]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5539 entries, 0 to 5538
Data columns (total 22 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id                             5539 non-null   int64
 1   heure_de_debut                 5539 non-null   datetime64[ns]
 2   heure_de_fin                   5539 non-null   datetime64[ns]
 3   date                           5539 non-null   datetime64[ns]
 4   lieu_de_la_verification        5539 non-null   object
 5   appartenance_du_conducteur     5539 non-null   object
 6   type_de_verification           5539 non-null   object
 7   region                         5539 non-null   object
 8   presence_licence_transport     4664 non-null   object
 9   numero_licence                 4312 non-null   object
 10  presentation_permis_conduire   4642 non-null   object
 11  verification_liste_nominative  4559 non-null   object
 12  anomalie                       5539 non-null   object
 13  anomalie_de_chargement         907 non-null    object
 14  anomalie_de_vehicule           127 non-null    object
 15  is_surete                      5539 non-null   bool
 16  anomalie_suivi_de_tournee      15 non-null     object
 17  agences_antennes               5497 non-null   object
 18  tournee                        5539 non-null   object
 19  pda                            635 non-null    object
 20  jour                           5539 non-null   object
 21  heure_arrondie                 5539 non-null   object
dtypes: bool(1), datetime64[ns](3), int64(1), object(17)
memory usage: 914.3+ KB

In [110]:
def uniform_anomalies(df) :
    # Remplacer NaN
    df["anomalie_de_chargement"] = df["anomalie_de_chargement"].fillna("Aucune anomalie")
    
    # Split et nettoyage
    df["anomalie_list"] = df["anomalie_de_chargement"].apply(
        lambda x: [item.strip().rstrip(";") for item in x.split(";") if item.strip()]
    )
    
    # Mapping pour uniformiser
    mapping = {
        "Autre": "Autre",
        "Colis en cabine": "Colis en cabine",
        "Colis non scanné (prévu pour ce chauffeur-livreur)": "Colis non scanné",
        "Colis non prévu pour ce chauffeur-livreur": "Colis non prévu",
        "Colis non prévu pour ce chauffeur-livreur (prévenir sans délai le service sûreté)": "Colis non prévu",
        "Adhésif Colis Privé dans le véhicule": "Adhésif Colis Privé"
    }
    
    df["anomalie_de_chargement"] = df["anomalie_list"].apply(
        lambda lst: [mapping.get(item, item) for item in lst]
    )
    
    # Remplacer NaN
    df["anomalie_de_vehicule"] = df["anomalie_de_vehicule"].fillna("Aucune anomalie")
    
    # Split et nettoyage
    df["anomalie_vehicule_list"] = df["anomalie_de_vehicule"].apply(
        lambda x: [item.strip().rstrip(";") for item in x.split(";") if item.strip()]
    )

    # Mapping pour uniformiser
    mapping_vehicule = {
        "Clef laissé sur le contact": "Clef laissée sur le contact",
        "Clef laissée sur le contact": "Clef laissée sur le contact",
        "Défaut de verrouillage": "Défaut de verrouillage",
        "Etat général": "Etat général",
        "Manque séparation cabine/caisse": "Manque séparation cabine/caisse",
        "Passager non autorisé": "Passager non autorisé",
        "Véhicule vitré": "Véhicule vitré"
    }
    
    df["anomalie_de_vehicule"] = df["anomalie_vehicule_list"].apply(
        lambda lst: [mapping_vehicule.get(item, item) for item in lst]
    )
    
    # Remplacer NaN
    df["anomalie_suivi_de_tournee"] = df["anomalie_suivi_de_tournee"].fillna("Aucune anomalie")
    
    # Split et nettoyage
    df["anomalie_tournee_list"] = df["anomalie_suivi_de_tournee"].apply(
        lambda x: [item.strip().rstrip(";") for item in x.split(";") if item.strip()]
    )
    
    # Mapping pour uniformiser
    mapping_tournee = {
        "Colis en cabine": "Colis en cabine",
        "Colis non autorisé": "Colis non autorisé",
        "Défaut de verrouillage": "Défaut de verrouillage",
        "Moteur tournant ou clef sur le contact": "Moteur tournant ou clef sur le contact"
    }
    
    df["anomalie_suivi_de_tournee"] = df["anomalie_tournee_list"].apply(
        lambda lst: [mapping_tournee.get(item, item) for item in lst]
    )

    return df

In [111]:
df = uniform_anomalies(df)

In [114]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5539 entries, 0 to 5538
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id                             5539 non-null   int64
 1   heure_de_debut                 5539 non-null   datetime64[ns]
 2   heure_de_fin                   5539 non-null   datetime64[ns]
 3   date                           5539 non-null   datetime64[ns]
 4   lieu_de_la_verification        5539 non-null   object
 5   appartenance_du_conducteur     5539 non-null   object
 6   type_de_verification           5539 non-null   object
 7   region                         5539 non-null   object
 8   presence_licence_transport     4664 non-null   object
 9   numero_licence                 4312 non-null   object
 10  presentation_permis_conduire   4642 non-null   object
 11  verification_liste_nominative  4559 non-null   object
 12  anomalie                       5539 non-null   object
 13  anomalie_de_chargement         5539 non-null   object
 14  anomalie_de_vehicule           5539 non-null   object
 15  is_surete                      5539 non-null   bool
 16  anomalie_suivi_de_tournee      5539 non-null   object
 17  agences_antennes               5497 non-null   object
 18  tournee                        5539 non-null   object
 19  pda                            635 non-null    object
 20  jour                           5539 non-null   object
 21  heure_arrondie                 5539 non-null   object
 22  anomalie_list                  5539 non-null   object
 23  anomalie_vehicule_list         5539 non-null   object
 24  anomalie_tournee_list          5539 non-null   object
dtypes: bool(1), datetime64[ns](3), int64(1), object(20)
memory usage: 1.0+ MB

In [113]:
# Sauvegarder le DataFrame dans un CSV
df.to_csv("verif_concordance.csv", index=False, date_format="%Y-%m-%d %H:%M:%S")
print("Fichier 'verif_concordance.csv' généré avec succès.")

Fichier 'verif_concordance.csv' généré avec succès.